[package]
name = "day9"
version = "0.1.0"
authors = ["coriolinus <coriolinus@gmail.com>"]

[lib]
name = "day9lib"
path = "src/lib.rs"

[[bin]]
name = "day9bin"
path = "src/bin.rs"

[dependencies]
util = { path = "../util"}
permutohedron = "^0.1.7"
